package sh.swisschili.chat.client;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddGroupDialog extends JDialog {
    private JPanel rootPanel;
    private JTextField groupName;
    private JTextField server;
    private JButton cancelButton;
    private JButton addButton;

    public interface AddGroupListener {
        void groupAdded(String groupName, String server);
    }

    public AddGroupDialog(AddGroupListener listener) {
        add(rootPanel);

        setMinimumSize(new Dimension(300, 160));

        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkInputs();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkInputs();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkInputs();
            }

            private void checkInputs() {
                addButton.setEnabled(!groupName.getText().isBlank() && !server.getText().isBlank());
            }
        };

        groupName.getDocument().addDocumentListener(documentListener);
        server.getDocument().addDocumentListener(documentListener);

        cancelButton.addActionListener(e -> setVisible(false));

        addButton.addActionListener(e -> {
            setVisible(false);
            listener.groupAdded(groupName.getText(), server.getText());
        });

        getRootPane().setDefaultButton(addButton);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        rootPanel.setEnabled(true);
        final JLabel label1 = new JLabel();
        label1.setText("Group Name");
        CellConstraints cc = new CellConstraints();
        rootPanel.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setText("Server");
        rootPanel.add(label2, cc.xy(1, 3));
        groupName = new JTextField();
        rootPanel.add(groupName, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        server = new JTextField();
        rootPanel.add(server, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        rootPanel.add(panel1, cc.xy(3, 5));
        addButton = new JButton();
        addButton.setEnabled(false);
        addButton.setText("Add");
        panel1.add(addButton, cc.xy(1, 3));
        cancelButton = new JButton();
        cancelButton.setEnabled(true);
        cancelButton.setText("Cancel");
        panel1.add(cancelButton, cc.xy(3, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
